import Layout from '@/components/layout/Layout/Layout';
import OrderSummary from '@/components/widgets/OrderSummary/index';
import Sidebar from '@/components/layout/Sidebar/index';
import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';

const space = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${space.className} antialiased`}>
        <Layout sidebar={<Sidebar />} main={children} aside={<OrderSummary />} />
      </body>
    </html>
  );
}
